foreach(hook player monkey presentation revenant dlss)
 add_executable(${hook}_hook_installation_tests tests/${hook}_hook_installation_tests.cpp)
 target_compile_features(${hook}_hook_installation_tests PRIVATE cxx_std_17)
 target_compile_definitions(${hook}_hook_installation_tests PRIVATE WIN32_LEAN_AND_MEAN NOMINMAX VK_NO_PROTOTYPES XR_NO_PROTOTYPES XR_USE_GRAPHICS_API_VULKAN)
 target_include_directories(${hook}_hook_installation_tests PRIVATE third-party/minhook/include third-party/openxr-sdk/include third-party/vulkan-headers/include)
 add_test(NAME ${hook}_hook_installation COMMAND ${hook}_hook_installation_tests)
 set_tests_properties(${hook}_hook_installation PROPERTIES TIMEOUT 120)
endforeach()
add_executable(dlss_hook_clean_tests tests/dlss_hook_installation_tests.cpp)
target_compile_features(dlss_hook_clean_tests PRIVATE cxx_std_17)
target_compile_definitions(dlss_hook_clean_tests PRIVATE ARGENT_CLEAN_RELEASE WIN32_LEAN_AND_MEAN NOMINMAX VK_NO_PROTOTYPES XR_NO_PROTOTYPES XR_USE_GRAPHICS_API_VULKAN)
target_include_directories(dlss_hook_clean_tests PRIVATE third-party/minhook/include third-party/openxr-sdk/include third-party/vulkan-headers/include)
add_test(NAME dlss_hook_clean COMMAND dlss_hook_clean_tests)
set_tests_properties(dlss_hook_clean PROPERTIES TIMEOUT 120)
add_executable(eternal_haptics_weapon_tests tests/eternal_haptics_weapon_tests.cpp)
target_compile_features(eternal_haptics_weapon_tests PRIVATE cxx_std_17)
add_test(NAME eternal_haptics_weapon COMMAND eternal_haptics_weapon_tests)
